### ISSUE TITLE
gevent wsgi deprecated use pywsgi

### ISSUE THREAD

**Issue by yashh** [toastdriven/itty#11]
I think the gevent server adapter must be using pywsgi instead of wsgi as wsgi is now removed and pointed to pywsgi...

```
from gevent import pywsgi
pywsgi.WSGIServer((host, int(port)), handle_request).serve_forever()
```

**Comment by toastdriven** [comment]
I didn't know the regular `wsgi` was deprecated, but the `pywsgi` is much better IMO anyhow. Fixed in SHA: 629cf5a69be69520e7f59b7a482c8a3bdb5584ed
