### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by husio** [toastdriven/itty#14]
Hi,
I've add Python3 support. It's FYI not a pull request because it breaks 2.x compability. Anyway, here's the commit https://github.com/husio/itty/commit/9c81330e89d82fb7e0b778c55991f04f302c2e4d

**Comment by kennethreitz** [comment]
FYI, % formatting works fine in Python 3.

**Comment by husio** [comment]
I know, but `.format` method is preffered way of string formatting in Python 3.x.

**Comment by kennethreitz** [comment]
Gotcha. My point is you could support both in the same codebase pretty easily :)

**Comment by husio** [comment]
You're right, but all I wanted is to run itty with my python 3.2 application. So I've made the port. I don't care about the backward compability, because supporting both 2.x and 3.x would make itty code looks ugly. And I think this is worse than single branch (2.x/3.x) support.

**Comment by ranaroussi** [comment]
Thanks for the port to 3. Works great under 3.4
