### ISSUE TITLE
JSON content-type

### ISSUE THREAD

**Issue by ghost** [toastdriven/itty#2]
Hi! What about generating json or xml content-type output?

**Comment by toastdriven** [comment]
Sorry for the horrifically slow response. I never got a notification of this issue. I'll try to address it within the next week or so.

**Comment by toastdriven** [comment]
I hate to say it but I'm not particularly excited about adding either of these as an option. The reason why is that it's already very doable. I've added an example script in SHA: 22421f49766f7102117d9749d3be03d107168741
