### ISSUE TITLE
Fix static file example

### ISSUE THREAD

**Issue by defunkt** [toastdriven/itty#4]
The static file example doesn't seem to actually set the content type. Here's a fix:

http://github.com/defunkt/itty/commit/fix_static_file_example

**Comment by toastdriven** [comment]
Sorry for the delay on this. This was already on my TODO list but hadn't made it to the issue tracker.

That link doesn't actually work for me. Help?

**Comment by defunkt** [comment]
Link should work now, sorry about that!

**Comment by toastdriven** [comment]
Fixed in SHA: 9b33b3b97e5908970241a1cd6ad0f669dc2baef7 & SHA: dde698a7e6a0fc9c16787d91a0142ddc0e4177a1
